import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { describe, expect, it } from "vitest";
import removeLegacyGeneratedDocs from "./legacyGeneratedDocs.js";

async function prepareDocs(files) {
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "pob-"));
  if (files) {
    await fs.mkdir(path.join(tmpDir, "docs"), { recursive: true });
    for (const file of files) {
      await fs.writeFile(path.join(tmpDir, "docs", file), "");
    }
  }
  return tmpDir;
}

const exists = (docsPath) =>
  fs
    .stat(docsPath)
    .then(() => true)
    .catch(() => false);

const run = (tmpDir) =>
  removeLegacyGeneratedDocs((destination) => path.join(tmpDir, destination));

describe("removeLegacyGeneratedDocs", () => {
  it.each([".nojekyll", "index.html", "coverage.lcov"])(
    "removes docs generated by typedoc or coverage, detected by %s",
    async (marker) => {
      const tmp = await prepareDocs([marker]);
      run(tmp);
      expect(await exists(path.join(tmp, "docs"))).toBe(false);
    },
  );

  it("removes docs detected by the typedoc assets directory", async () => {
    const tmp = await prepareDocs([]);
    await fs.mkdir(path.join(tmp, "docs/assets"), { recursive: true });
    run(tmp);
    expect(await exists(path.join(tmp, "docs"))).toBe(false);
  });

  it("keeps hand written documentation", async () => {
    const tmp = await prepareDocs(["guide.md", "README.md"]);
    run(tmp);
    expect(await fs.readdir(path.join(tmp, "docs"))).toEqual([
      "README.md",
      "guide.md",
    ]);
  });

  it("does nothing when there is no docs directory", async () => {
    const tmp = await prepareDocs(undefined);
    expect(() => run(tmp)).not.toThrow();
    expect(await exists(path.join(tmp, "docs"))).toBe(false);
  });
});
