import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { create as createMemFs } from "mem-fs";
import { create as createEditor } from "mem-fs-editor";
import {
  extractLibReadmeContent,
  extractMonorepoReadmeContent,
} from "./readmeContent.js";
import { copyAndFormatTpl } from "./writeAndFormat.js";

const templatePath = (generator) =>
  fileURLToPath(
    new URL(
      `../generators/${generator}/templates/README.md.ejs`,
      import.meta.url,
    ),
  );

// renders the README exactly as the generator writes it: template, then oxfmt
async function render(generator, options) {
  const fs = createEditor(createMemFs());
  const destinationPath = "/virtual/README.md";
  await copyAndFormatTpl(fs, templatePath(generator), destinationPath, options);
  return fs.read(destinationPath);
}

const packages = [
  { name: "pkg-a", description: "First package" },
  { name: "pkg-b", description: "Second package" },
];

const renderMonorepo = (content, { title = "a monorepo" } = {}) =>
  render("monorepo/workspaces", {
    title,
    description: "",
    packages,
    ci: false,
    content,
  });

const renderLib = (content, options = {}) =>
  render("lib/readme", {
    title: "pkg-a",
    privatePackage: false,
    packageName: "pkg-a",
    camelCaseProjectName: "pkgA",
    description: "First package",
    gitHost: "github",
    gitAccount: "someone",
    gitName: "pkg-a",
    codecov: false,
    documentation: false,
    documentationUrl: undefined,
    testing: false,
    ci: false,
    ...options,
    content,
  });

const proseBody = `Every tool here answers the same two questions:

- **why is this duplicated?** — which dependents force several versions.
- **dedupe it** — compute the fixes and apply them.

## Usage

Run it.`;

const headingBody = `## About

Some text, with **bold**.`;

describe("extractMonorepoReadmeContent", () => {
  it.each([
    ["a body starting with a heading", headingBody],
    ["a body starting with prose", proseBody],
  ])("keeps %s through regeneration", async (_, body) => {
    const readme = await renderMonorepo(body);
    expect(extractMonorepoReadmeContent(readme)).toBe(body);
    // a second run is stable
    expect(await renderMonorepo(extractMonorepoReadmeContent(readme))).toBe(
      readme,
    );
  });

  it("keeps the body when the title contains # or *", async () => {
    const readme = await renderMonorepo(proseBody, {
      title: "C# tools, **bold**",
    });
    expect(extractMonorepoReadmeContent(readme)).toBe(proseBody);
  });

  it("extracts nothing from a README without a body", async () => {
    expect(extractMonorepoReadmeContent(await renderMonorepo(""))).toBe("");
  });

  // pm-tools README: hand-written prose right after the table lost everything
  // up to the first `*`, i.e. the paragraph and the first bullet's `- `
  it("strips a hand-edited header and keeps the prose after the table", () => {
    const readme = `<h1 align="center">
  pm-tools
</h1>

<p align="center">
  Find out why a dependency is duplicated in a lockfile, and dedupe it.
</p>

<h3>📦 Packages</h3>

This repository is a monorepo managed with [bun workspaces](https://bun.com/docs/install/workspaces).

| Package               | Version | Description      |
| --------------------- | ------- | ---------------- |
| [pkg-a](packages/pkg-a) |         | First package    |

${proseBody}
`;
    expect(extractMonorepoReadmeContent(readme)).toBe(proseBody);
  });

  it("falls back to the first heading for a README not generated by pob", () => {
    expect(extractMonorepoReadmeContent("# title\n\nintro\n\n## Usage\n")).toBe(
      "## Usage",
    );
  });
});

describe("extractLibReadmeContent", () => {
  it.each([
    ["a body starting with a heading", headingBody, {}],
    ["a body starting with prose", proseBody, {}],
    [
      "a description containing # or *",
      headingBody,
      { description: "C# **x**" },
    ],
    ["no description", proseBody, { description: undefined }],
    [
      "an empty badges block",
      proseBody,
      { privatePackage: true, gitHost: undefined },
    ],
  ])(
    "keeps the body with %s through regeneration",
    async (_, body, options) => {
      const readme = await renderLib(body, options);
      expect(extractLibReadmeContent(readme)).toBe(body);
      expect(await renderLib(extractLibReadmeContent(readme), options)).toBe(
        readme,
      );
    },
  );

  it("strips legacy badges reference links", () => {
    const readme = `<h1 align="center">
  pkg-a
</h1>

## Usage

Run it.

[npm-image]: https://img.shields.io/npm/v/pkg-a.svg
`;
    expect(extractLibReadmeContent(readme)).toBe("## Usage\n\nRun it.");
  });
});
