import basePobConfig, {
  createOxlintConfigs,
  isOxlintConfigExtended,
  tsExtensions,
} from "@pob/eslint-config";
import pobPlugin from "@pob/eslint-plugin";
import { createNodeResolver } from "eslint-plugin-import-x";
import oxlintReactNativeWebConfig from "../oxlint/react-native-web.json" with { type: "json" };
import oxlintReactNativeConfig from "../oxlint/react-native.json" with { type: "json" };
import oxlintReactConfig from "../oxlint/react.json" with { type: "json" };
import importPluginOverrideConfig from "./plugins/import.js";
import jsxA11yConfigs from "./plugins/jsx-a11y.js";
import reactHooksConfigs from "./plugins/react-hooks.js";
import reactConfigs from "./plugins/react.js";

export { apply, applyTs } from "@pob/eslint-config";

const { configs } = basePobConfig;

// react.json is extended by React projects, once regenerated by pob: until
// then its rules stay in eslint, and import-x/extensions is re-enabled with
// the react options after the oxlint turn-off of @pob/eslint-config.
const oxlintReact = isOxlintConfigExtended(
  "@pob/eslint-config-typescript-react/oxlint/react.json",
);

// react-native.json and react-native-web.json replace the import-x/extensions
// options of the matching configs, extended after react.json
const oxlintReactNative =
  oxlintReact &&
  isOxlintConfigExtended(
    "@pob/eslint-config-typescript-react/oxlint/react-native.json",
  );
const oxlintReactNativeWeb =
  oxlintReact &&
  isOxlintConfigExtended(
    "@pob/eslint-config-typescript-react/oxlint/react-native-web.json",
  );

// turns off the rules of react.json, and those of @pob/eslint-config again as
// the react configs re-enable import-x/extensions
const oxlintReactConfigs = createOxlintConfigs([
  oxlintReactConfig,
  ...(oxlintReactNative ? [oxlintReactNativeConfig] : []),
  ...(oxlintReactNativeWeb ? [oxlintReactNativeWebConfig] : []),
]);

/**
 * @param {import("typescript-eslint").ConfigArray} base
 * @returns {import("typescript-eslint").ConfigArray}
 */
const createConfig = (base) => [
  ...base,
  importPluginOverrideConfig,

  ...[
    pobPlugin.configs.react,
    {
      settings: {
        "import-x/resolver-next": [
          createNodeResolver({
            extensions: [
              ".mjs",
              ".js",
              ".json",
              ".ts",
              ".tsx",
              ".d.ts",
              ".d.tsx",
            ],
          }),
        ],
      },
      rules: {
        "import-x/extensions": [
          "error",
          "always",
          {
            ignorePackages: true,
            pattern: {
              js: "always",
              cjs: "always",
              mjs: "always",
              cts: "always",
              mts: "always",
              ts: "never",
              tsx: "never",
            },
          },
        ],
        // "react/jsx-filename-extension": ["error", { extensions: ["tsx"] }],
      },
    },
    ...reactConfigs,
    ...reactHooksConfigs,
    ...jsxA11yConfigs,
  ].map((config) => ({
    ...config,
    files: [`**/*.${tsExtensions}`],
  })),
  ...(oxlintReact ? oxlintReactConfigs : []),
];

/**
 * @satisfies {{ configs: Record<string, import("typescript-eslint").ConfigArray> }}
 */
export default {
  configs: {
    base: createConfig(configs.baseModule),
    node: createConfig(configs.node),

    allowUnsafe: configs.allowUnsafe,
    allowUnsafeAsWarn: configs.allowUnsafeAsWarn,
    allowImplicitReturnType: configs.allowImplicitReturnType,
    app: configs.app,

    monorepo: configs.monorepo,

    // for projects extending react.json from a nested .oxlintrc.json, like
    // this repo's test-lint: apply it last on the same files
    oxlint: oxlintReactConfigs,

    "react-native": [
      {
        settings: {
          "import-x/resolver-next": [
            createNodeResolver({
              extensions: [
                ".js", // needed to resolve js files from node_modules
                ".cjs",
                ".mjs",
                ".ts",
                ".tsx",
                ".ios.ts",
                ".ios.tsx",
                ".android.ts",
                ".android.tsx",
              ],
              conditionNames: ["import", "react-native"],
            }),
          ],
        },
        rules: oxlintReactNative
          ? {}
          : {
              "import-x/extensions": [
                "error",
                "always",
                {
                  ignorePackages: true,
                  pattern: {
                    js: "always",
                    cjs: "always",
                    mjs: "always",
                    cts: "always",
                    mts: "always",
                    ts: "never",
                    tsx: "never",
                  },
                },
              ],
            },
      },
    ],

    "react-native-web": [
      {
        settings: {
          "import-x/resolver-next": [
            createNodeResolver({
              extensions: [
                ".js", // needed to resolve js files from node_modules
                ".cjs",
                ".mjs",
                ".ts",
                ".tsx",
                ".web.ts",
                ".web.tsx",
              ],
              conditionNames: ["import", "browser"],
            }),
          ],
        },
        rules: {
          ...(oxlintReactNativeWeb
            ? {}
            : {
                "import-x/extensions": [
                  "error",
                  "always",
                  {
                    ignorePackages: true,
                    pattern: {
                      js: "always",
                      cjs: "always",
                      mjs: "always",
                      cts: "always",
                      mts: "never",
                      ts: "never",
                      tsx: "never",
                    },
                  },
                ],
              }),
          "import-x/no-unresolved": [
            "error",
            {
              ignore: [
                // allow react-native as it is replaced by react-native-web and typed by @types/react-native. react-native lib does not need to be installed in that case
                "react-native",
              ],
            },
          ],
        },
      },
    ],
  },
};
