defaultSemverRangePrefix: ^
enableMessageNames: false
nodeLinker: node-modules
nmMode: hardlinks-global
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
yarnPath: .yarn/releases/yarn-3.6.3.cjs
