compressionLevel: mixed
defaultSemverRangePrefix: ^
enableGlobalCache: true
enableMessageNames: false
nodeLinker: node-modules
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
