compressionLevel: mixed
defaultSemverRangePrefix: ^
enableGlobalCache: true
enableMessageNames: false
nodeLinker: node-modules
plugins:
  - checksum: >-
      ca86e4b7fd8551b99d3a0b03d616b0502679ba1f8977588a1f867b6acc7b81c8c92c82dc6dadc4d814bf05e1c1680a09b5556ac92d56f63fef102bd29180bc0c
    path: .yarn/plugins/@yarnpkg/plugin-conventional-version.cjs
    spec: >-
      https://raw.githubusercontent.com/christophehurpeau/yarn-plugin-conventional-version/main/bundles/@yarnpkg/plugin-conventional-version.cjs
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
