compressionLevel: mixed
defaultSemverRangePrefix: ^
enableGlobalCache: true
enableMessageNames: false
nodeLinker: node-modules
plugins:
  - checksum: >-
      02ecaa8435872491d41e8b3df50569d9f54d72ab78eed3103e5b21f5c3066935c62356fdd9967c8ef32b9e4c40f308b9f5f35d21019da89d2ed11819c04da632
    path: .yarn/plugins/@yarnpkg/plugin-conventional-version.cjs
    spec: >-
      https://raw.githubusercontent.com/christophehurpeau/yarn-plugin-conventional-version/main/bundles/@yarnpkg/plugin-conventional-version.cjs
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
