allowBuilds:
  esbuild: true
  unrs-resolver: true
dedupePeerDependents: true
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@pob/*"
  - pob-dependencies
  - alouette
  - alouette-icons
  - nightingale
  - nightingale-logger
  - check-package-dependencies
  # Renovate security update: js-yaml@5.2.2
  - js-yaml@5.2.2
packages:
  - packages/*
  - "@pob/*"
  - pob-examples/*
savePrefix: ^
nodeLinker: hoisted
