import fs from "node:fs";
import path from "node:path";
import tseslint from "typescript-eslint";
import oxlintBaseConfig from "../oxlint/base.json" with { type: "json" };
import oxlintModuleConfig from "../oxlint/module.json" with { type: "json" };
import oxlintNodeConfig from "../oxlint/node.json" with { type: "json" };
import oxlintTypescriptConfig from "../oxlint/typescript.json" with { type: "json" };
import baseConfigs from "./_base.js";
import baseCommonjsConfig from "./base/commonjs.js";
import baseModuleConfig from "./base/module.js";
import nodePluginCommonjsConfigs from "./node/commonjs.js";
import nodePluginModuleConfigs from "./node/module.js";
import nodeTypescriptConfigs from "./node/typescript.js";
import allowImplicitReturnTypeConfig from "./overrides/allow-implicit-return-type.js";
import allowUnsafeAsWarnConfig from "./overrides/allow-unsafe-as-warn.js";
import allowUnsafeConfig from "./overrides/allow-unsafe.js";
import appConfig from "./overrides/app.js";
import scriptsOverrideConfig from "./overrides/scripts.js";
import {
  testOverrideConfigsWithTypescript,
  testOverrideConfigsWithoutTypescript,
} from "./overrides/test.js";
import toolsProjectConfig from "./overrides/tools-project.js";
import importPluginBaseConfigs from "./plugins/import/import-base.js";
import importPluginCommonjsConfig from "./plugins/import/import-commonjs.js";
import importPluginModuleConfig from "./plugins/import/import-module.js";
import typescriptReplaceEslintConfig from "./plugins/typescript-eslint/typescript-eslint-replace-eslint.js";
import typescriptReplaceUnicornConfig from "./plugins/typescript-eslint/typescript-eslint-replace-unicorn.js";
import typescriptPluginRulesConfig from "./plugins/typescript-eslint/typescript-eslint-rules.js";
import typescriptRulesConfig from "./rules/typescript.js";
import { apply } from "./utils/apply.js";
import {
  createOxlintDisableDirectivesProcessor,
  getOxlintConfigRuleNames,
  oxlintToEslintRuleNames,
} from "./utils/oxlint.js";

export { apply } from "./utils/apply.js";

export const tsExtensions = "{ts,cts,mts,tsx}";

export const applyTs = (options) =>
  apply({
    extensions: tsExtensions,
    ...options,
  });

// @ts-expect-error -- missing files declaration
const tsFiles = tseslint.configs.strictTypeChecked[1].files;
if (!tsFiles) {
  throw new Error(
    'Unexpected "tseslint.configs.strictTypeChecked[1].files" value',
  );
}

const extensions = "{js,cjs,mjs}";

const oxlintrcPath = path.resolve(".oxlintrc.json");
const oxlintrc = fs.existsSync(oxlintrcPath)
  ? fs.readFileSync(oxlintrcPath, "utf8")
  : undefined;

// typescript.json is extended by TypeScript projects only, once regenerated by
// pob: until then its rules stay in eslint.
const oxlintTypescript =
  oxlintrc?.includes("@pob/eslint-config/oxlint/typescript.json") ?? false;

// module.json is extended by ES module projects (not configs.nodeCommonjs),
// once regenerated by pob: until then its rules stay in eslint.
const oxlintModule =
  oxlintrc?.includes("@pob/eslint-config/oxlint/module.json") ?? false;

// node.json is extended by projects using the node configs, once regenerated
// by pob: until then its rules stay in eslint.
const oxlintNode =
  oxlintrc?.includes("@pob/eslint-config/oxlint/node.json") ?? false;

// the shared oxlint configs the project extends
const oxlintSharedConfigs = oxlintrc
  ? [
      oxlintBaseConfig,
      ...(oxlintModule ? [oxlintModuleConfig] : []),
      ...(oxlintNode ? [oxlintNodeConfig] : []),
      ...(oxlintTypescript ? [oxlintTypescriptConfig] : []),
    ]
  : [];

const oxlintEslintRuleNames = new Set(
  oxlintSharedConfigs
    .flatMap((config) => getOxlintConfigRuleNames(config))
    .flatMap((ruleName) => oxlintToEslintRuleNames(ruleName)),
);

// turns off the rules checked by oxlint, must be applied last. Only when the
// project runs oxlint, so the rules are still checked by eslint otherwise.
const oxlintConfigs = oxlintrc
  ? [
      {
        name: "@pob/eslint-config/oxlint",
        rules: Object.fromEntries(
          [...oxlintEslintRuleNames].map((ruleName) => [ruleName, "off"]),
        ),
      },
      {
        name: "@pob/eslint-config/oxlint-disable-directives",
        files: ["**/*.{js,cjs,mjs,jsx,ts,cts,mts,tsx}"],
        processor: createOxlintDisableDirectivesProcessor(
          oxlintEslintRuleNames,
        ),
      },
      // oxlint runs every type-aware rule: eslint no longer needs to build the
      // TypeScript program, its most expensive part
      ...(oxlintTypescript
        ? [
            {
              name: "@pob/eslint-config/oxlint-typescript",
              files: [`**/*.${tsExtensions}`],
              languageOptions: {
                parserOptions: { project: false, projectService: false },
              },
            },
          ]
        : []),
    ]
  : [];

/**
 * Removes the rules checked by oxlint from configs applied after
 * `oxlintConfigs`, like the overrides a project selects. Their oxlint
 * counterparts are extended in .oxlintrc.json (`oxlint/allow-unsafe.json`,
 * ...).
 *
 * @template {{ rules?: Record<string, unknown> }} T
 * @param {T[]} configs
 * @returns {T[]}
 */
const withoutOxlintRules = (configs) =>
  configs.map((config) =>
    config.rules
      ? {
          ...config,
          rules: Object.fromEntries(
            Object.entries(config.rules).filter(
              ([ruleName]) => !oxlintEslintRuleNames.has(ruleName),
            ),
          ),
        }
      : config,
  );

// without the TypeScript program, only the import-x settings are left
const {
  languageOptions: _toolsProjectLanguageOptions,
  ...toolsProjectSettings
} = toolsProjectConfig;
const toolsProjectConfigs = [
  oxlintTypescript ? toolsProjectSettings : toolsProjectConfig,
];

const testFiles = [
  `**/*.{test,test-e2e,spec}.${extensions}`,
  `**/__tests__/**/*.${extensions}`,
  `**/__mocks__/**/*.${extensions}`,
];

const tsTestFiles = [
  `**/*.test.${tsExtensions}`,
  `**/*.test-e2e.${tsExtensions}`,
  `**/__tests__/**/*.${tsExtensions}`,
  `**/__mocks__/**/*.${tsExtensions}`,
];

const typescriptConfigs = [
  ...applyTs({
    filesOverridesIf: [tsFiles],
    configs: [
      ...tseslint.configs.strictTypeChecked,
      typescriptReplaceUnicornConfig,
      typescriptReplaceEslintConfig,
      typescriptPluginRulesConfig,
      typescriptRulesConfig,
    ],
  }),
  ...apply({
    files: tsTestFiles,
    configs: testOverrideConfigsWithTypescript,
  }),
];

/** @deprecated */
const nodeCommonjs = [
  ...baseConfigs,
  ...apply({
    mode: "keep-files-if-exists",
    files: ["**/*.{js,cjs,mjs,mts,ts,tsx,cts}"],
    configs: [
      baseCommonjsConfig,
      ...importPluginBaseConfigs,
      importPluginCommonjsConfig,
      ...nodePluginCommonjsConfigs,
    ],
  }),

  ...apply({
    extensions,
    mode: "directory",
    files: ["**/scripts/"],
    configs: [scriptsOverrideConfig],
  }),

  ...apply({
    files: ["**/*.{mjs,mts}"],
    mode: "keep-files-if-exists",
    configs: [
      baseModuleConfig,
      importPluginModuleConfig,
      ...nodePluginModuleConfigs,
    ],
  }),

  ...apply({
    files: testFiles,
    configs: testOverrideConfigsWithoutTypescript,
  }),
];

const baseModule = [
  ...baseConfigs,
  ...apply({
    mode: "keep-files-if-exists",
    files: ["**/*.{js,mjs,cjs,mts,ts,tsx,cts}"],
    configs: [
      baseModuleConfig,
      ...importPluginBaseConfigs,
      importPluginModuleConfig,
    ],
  }),

  ...apply({
    mode: "keep-files-if-exists",
    files: ["**/*.{cjs,cts}"],
    configs: [baseCommonjsConfig, importPluginCommonjsConfig],
  }),

  ...typescriptConfigs,
];

const nodeModule = [
  ...baseModule,
  ...apply({
    mode: "keep-files-if-exists",
    files: ["**/*.{js,mjs,mts,ts,tsx}"],
    configs: [...nodePluginModuleConfigs],
  }),

  ...apply({
    extensions,
    mode: "directory",
    files: ["**/scripts/"],
    configs: [scriptsOverrideConfig],
  }),

  ...apply({
    mode: "keep-files-if-exists",
    files: ["**/*.{cjs,cts}"],
    configs: [...nodePluginCommonjsConfigs],
  }),

  ...nodeTypescriptConfigs,
];

/**
 * @satisfies {{ configs: Record<string, import("typescript-eslint").ConfigArray> }}
 */
export default {
  configs: {
    baseModule: [
      ...baseModule,
      ...apply({
        extensions,
        mode: "directory",
        files: ["**/scripts/"],
        configs: [...nodePluginModuleConfigs, scriptsOverrideConfig],
      }),
      ...oxlintConfigs,
    ],
    /** @deprecated */
    nodeModule: [...nodeModule, ...oxlintConfigs],
    /** @deprecated */
    nodeCommonjs: [...nodeCommonjs, ...oxlintConfigs],
    node: [...nodeModule, ...oxlintConfigs],

    allowImplicitReturnType: applyTs({
      configs: withoutOxlintRules([allowImplicitReturnTypeConfig]),
    }),

    allowUnsafe: applyTs({
      configs: withoutOxlintRules([allowUnsafeConfig]),
    }),

    allowUnsafeAsWarn: applyTs({
      configs: withoutOxlintRules([allowUnsafeAsWarnConfig]),
    }),

    app: applyTs({
      configs: withoutOxlintRules([appConfig]),
    }),

    monorepo: toolsProjectConfigs,
    toolsProject: toolsProjectConfigs,
  },
};
