export const appIgnorePaths = {
  alp: (config) => ["# alp paths", "/build", "/public", "/data"],
  "next.js": (config, pkg) =>
    [
      "# next.js paths",
      "/.next",
      "/out",
      "/build",
      "/.env.local",
      pkg?.dependencies?.tamagui ? "# tamagui" : undefined,
      pkg?.dependencies?.tamagui ? "/.tamagui" : undefined,
    ].filter(Boolean),
  remix: (config) => ["# remix paths", "/.cache", "/build", "/public/build"],
  vite: (config) => ["/build"],
  node: (config) => (config.distribute ? [] : ["/build"]),
  "node-library": (config) => ["/build"],
  "untranspiled-library": (config) => [],
  "alp-node": (config) => ["/build"],
  other: (config) => [],
  storybook: (config) => ["/.storybook/storybook.requires.ts"],
  expo: (config) => [
    "/.expo/",
    "/src/tamagui-web.css",
    "/android/",
    "/ios/",
    "/dist/",
    "*.jks",
    "*.p8",
    "*.p12",
    "*.key",
    "*.mobileprovision",
    "*.orig.*",
    "*.icon/",

    // only if option is enabled which is not by default
    // '# Temporary files created by Metro to check the health of the file watcher',
    // '/.metro-health-check*',
  ],
  "yarn-plugin": (config) => [],
};
